"""Build the master timeline shared by the visuals (video/src/timeline.js) and
the audio mix (audio/build/timeline.json).

Scene boundaries are snapped to the soundtrack's half-bar grid so every scene
change lands on the music, and each VO line is placed after its scene's
lead-in / minimum gap. Speech segments (clauses between pauses) are exported so
animations can be keyed to individual phrases.
"""
import json
import math
import os

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
BPM = 100.0
BEAT = 60.0 / BPM
GRID = BEAT * 2  # half-bar grid (1.2 s at 100 BPM)
FPS = 30


def snap_up(t, grid=GRID, slack=0.7):
    """Smallest grid point >= t - slack."""
    return math.ceil((t - slack) / grid - 1e-9) * grid


def main():
    script = json.load(open(os.path.join(HERE, "vo_script.json")))
    manifest = json.load(open(os.path.join(HERE, "build", "vo", "manifest.json")))
    t0 = 0.0
    scenes, lines = [], {}
    for scene in script["scenes"]:
        cursor = None
        placed = []
        for line in scene["lines"]:
            m = manifest[line["id"]]
            start = t0 + line.get("at", 0.0)
            if cursor is not None:
                start = max(start, cursor + line.get("gap", 0.4))
            end = start + m["duration"]
            segs = [[round(start + s, 3), round(start + e, 3)] for s, e in m["segments"]]
            entry = {"id": line["id"], "scene": scene["id"], "start": round(start, 3), "end": round(end, 3),
                     "segs": segs, "text": line["text"]}
            placed.append(entry)
            lines[line["id"]] = entry
            cursor = end
        natural_end = max(cursor + scene.get("tail", 1.0), t0 + scene.get("min", 0.0))
        end = snap_up(natural_end)
        scenes.append({"id": scene["id"], "start": round(t0, 3), "end": round(end, 3),
                       "lines": [p["id"] for p in placed]})
        t0 = end

    duration = t0
    timeline = {"fps": FPS, "bpm": BPM, "beat": BEAT, "duration": round(duration, 3), "scenes": scenes, "lines": lines}
    os.makedirs(os.path.join(HERE, "build"), exist_ok=True)
    json.dump(timeline, open(os.path.join(HERE, "build", "timeline.json"), "w"), indent=1)
    js = "// Generated by audio/build_timeline.py — do not edit by hand.\nexport default " + json.dumps(timeline, indent=1) + ";\n"
    open(os.path.join(ROOT, "video", "src", "timeline.js"), "w").write(js)

    for s in scenes:
        print(f"{s['id']:>7}  {s['start']:7.2f} -> {s['end']:7.2f}  ({s['end'] - s['start']:5.2f}s)")
        for lid in s["lines"]:
            l = lines[lid]
            print(f"           {lid:>3} {l['start']:7.2f} -> {l['end']:7.2f}  {l['text'][:70]}")
    m, s = divmod(duration, 60)
    print(f"TOTAL {duration:.2f}s  ({int(m)}:{s:05.2f})")


if __name__ == "__main__":
    main()
