// Generated by audio/build_timeline.py — do not edit by hand.
export default {
 "fps": 30,
 "bpm": 100.0,
 "beat": 0.6,
 "duration": 128.4,
 "scenes": [
  {
   "id": "hook",
   "start": 0.0,
   "end": 19.2,
   "lines": [
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6"
   ]
  },
  {
   "id": "search",
   "start": 19.2,
   "end": 39.6,
   "lines": [
    "s1",
    "s2",
    "s3"
   ]
  },
  {
   "id": "story",
   "start": 39.6,
   "end": 58.8,
   "lines": [
    "t1",
    "t2",
    "t3",
    "t4"
   ]
  },
  {
   "id": "vision",
   "start": 58.8,
   "end": 78.0,
   "lines": [
    "v1",
    "v2",
    "v3"
   ]
  },
  {
   "id": "agri",
   "start": 78.0,
   "end": 97.2,
   "lines": [
    "a1",
    "a2",
    "a3"
   ]
  },
  {
   "id": "docs",
   "start": 97.2,
   "end": 112.8,
   "lines": [
    "d1",
    "d2"
   ]
  },
  {
   "id": "finale",
   "start": 112.8,
   "end": 128.4,
   "lines": [
    "f1",
    "f2",
    "f3",
    "f4"
   ]
  }
 ],
 "lines": {
  "h1": {
   "id": "h1",
   "scene": "hook",
   "start": 1.3,
   "end": 2.455,
   "segs": [
    [
     1.33,
     2.35
    ]
   ],
   "text": "A creative brief."
  },
  "h2": {
   "id": "h2",
   "scene": "hook",
   "start": 2.905,
   "end": 3.965,
   "segs": [
    [
     2.935,
     3.845
    ]
   ],
   "text": "A child's toy."
  },
  "h3": {
   "id": "h3",
   "scene": "hook",
   "start": 4.415,
   "end": 5.415,
   "segs": [
    [
     4.445,
     5.295
    ]
   ],
   "text": "A camera feed."
  },
  "h4": {
   "id": "h4",
   "scene": "hook",
   "start": 5.865,
   "end": 7.075,
   "segs": [
    [
     5.895,
     6.955
    ]
   ],
   "text": "A stack of evidence."
  },
  "h5": {
   "id": "h5",
   "scene": "hook",
   "start": 8.075,
   "end": 11.17,
   "segs": [
    [
     8.105,
     9.455
    ],
    [
     9.805,
     11.085
    ]
   ],
   "text": "Not AI as a feature. AI as the product."
  },
  "h6": {
   "id": "h6",
   "scene": "hook",
   "start": 12.17,
   "end": 18.923,
   "segs": [
    [
     12.2,
     16.33
    ],
    [
     16.73,
     17.43
    ],
    [
     17.61,
     18.86
    ]
   ],
   "text": "Eagerworks AI Studio turns AI capabilities into real products, workflows and measurable outcomes."
  },
  "s1": {
   "id": "s1",
   "scene": "search",
   "start": 19.9,
   "end": 23.73,
   "segs": [
    [
     19.93,
     22.48
    ],
    [
     22.79,
     23.66
    ]
   ],
   "text": "A production team describes the location they need, in their own words."
  },
  "s2": {
   "id": "s2",
   "scene": "search",
   "start": 24.33,
   "end": 32.821,
   "segs": [
    [
     24.36,
     26.15
    ],
    [
     26.55,
     27.66
    ],
    [
     28.01,
     30.36
    ],
    [
     30.65,
     32.75
    ]
   ],
   "text": "AI parses every requirement, searches the catalog, evaluates each location against the brief, and returns a personalized shortlist."
  },
  "s3": {
   "id": "s3",
   "scene": "search",
   "start": 34.121,
   "end": 38.43,
   "segs": [
    [
     34.151,
     35.811
    ],
    [
     36.141,
     38.351
    ]
   ],
   "text": "Then the conversation keeps going, and every reply makes the results sharper."
  },
  "t1": {
   "id": "t1",
   "scene": "story",
   "start": 40.1,
   "end": 43.599,
   "segs": [
    [
     40.12,
     40.66
    ],
    [
     40.75,
     42.29
    ],
    [
     42.48,
     43.52
    ]
   ],
   "text": "AI can also turn something physical into something personal."
  },
  "t2": {
   "id": "t2",
   "scene": "story",
   "start": 44.099,
   "end": 46.382,
   "segs": [
    [
     44.129,
     46.289
    ]
   ],
   "text": "A child places a few pieces on a board."
  },
  "t3": {
   "id": "t3",
   "scene": "story",
   "start": 46.982,
   "end": 53.147,
   "segs": [
    [
     47.002,
     48.672
    ],
    [
     49.022,
     50.622
    ],
    [
     50.932,
     53.082
    ]
   ],
   "text": "The system recognizes each one, reasons about how they connect, and writes a story that's entirely theirs."
  },
  "t4": {
   "id": "t4",
   "scene": "story",
   "start": 54.247,
   "end": 57.212,
   "segs": [
    [
     54.277,
     55.367
    ],
    [
     55.637,
     57.127
    ]
   ],
   "text": "We build it end to end, from the app to the story engine."
  },
  "v1": {
   "id": "v1",
   "scene": "vision",
   "start": 59.2,
   "end": 61.845,
   "segs": [
    [
     59.23,
     60.29
    ],
    [
     60.47,
     61.76
    ]
   ],
   "text": "Some problems need more than an API call."
  },
  "v2": {
   "id": "v2",
   "scene": "vision",
   "start": 62.345,
   "end": 69.514,
   "segs": [
    [
     62.375,
     64.745
    ],
    [
     65.225,
     66.565
    ],
    [
     66.775,
     68.065
    ],
    [
     68.255,
     69.455
    ]
   ],
   "text": "For robotics, we build the vision stack itself: hand and face detection, camera and wrist tracking, and custom datasets."
  },
  "v3": {
   "id": "v3",
   "scene": "vision",
   "start": 70.214,
   "end": 74.715,
   "segs": [
    [
     70.244,
     72.294
    ],
    [
     72.644,
     74.634
    ]
   ],
   "text": "Then we train and benchmark every model, until the data is ready to teach a robot."
  },
  "a1": {
   "id": "a1",
   "scene": "agri",
   "start": 78.5,
   "end": 82.714,
   "segs": [
    [
     78.53,
     79.39
    ],
    [
     79.6,
     80.35
    ],
    [
     80.55,
     82.64
    ]
   ],
   "text": "Computer vision turns a camera into a live source of operational data."
  },
  "a2": {
   "id": "a2",
   "scene": "agri",
   "start": 83.264,
   "end": 88.609,
   "segs": [
    [
     83.294,
     84.724
    ],
    [
     85.014,
     86.494
    ],
    [
     86.714,
     88.544
    ]
   ],
   "text": "On a tractor, it detects, counts and measures every plant, and maps exactly where each one is."
  },
  "a3": {
   "id": "a3",
   "scene": "agri",
   "start": 90.109,
   "end": 96.018,
   "segs": [
    [
     90.139,
     91.069
    ],
    [
     91.369,
     94.139
    ],
    [
     94.509,
     95.929
    ]
   ],
   "text": "On the packing line, every pumpkin gets its own ID the moment it appears, and keeps it until it's counted."
  },
  "d1": {
   "id": "d1",
   "scene": "docs",
   "start": 97.7,
   "end": 108.399,
   "segs": [
    [
     97.73,
     99.31
    ],
    [
     99.7,
     101.15
    ],
    [
     101.48,
     105.58
    ],
    [
     105.9,
     106.87
    ],
    [
     107.06,
     108.34
    ]
   ],
   "text": "And when the work lives in documents, AI reads the evidence, maps it to frameworks like SOC 2 and ISO 27001, flags the gaps, and recommends what to fix."
  },
  "d2": {
   "id": "d2",
   "scene": "docs",
   "start": 108.999,
   "end": 111.922,
   "segs": [
    [
     109.029,
     110.559
    ],
    [
     110.819,
     111.859
    ]
   ],
   "text": "So teams know where they stand, before the auditor does."
  },
  "f1": {
   "id": "f1",
   "scene": "finale",
   "start": 113.4,
   "end": 117.699,
   "segs": [
    [
     113.43,
     114.31
    ],
    [
     114.69,
     115.92
    ],
    [
     116.09,
     117.62
    ]
   ],
   "text": "Different problems. One team that designs, builds and ships the whole system."
  },
  "f2": {
   "id": "f2",
   "scene": "finale",
   "start": 118.999,
   "end": 120.619,
   "segs": [
    [
     119.029,
     120.499
    ]
   ],
   "text": "Eagerworks AI Studio."
  },
  "f3": {
   "id": "f3",
   "scene": "finale",
   "start": 121.219,
   "end": 123.748,
   "segs": [
    [
     121.249,
     123.679
    ]
   ],
   "text": "From AI ideas to real-world products."
  },
  "f4": {
   "id": "f4",
   "scene": "finale",
   "start": 124.748,
   "end": 126.116,
   "segs": [
    [
     124.778,
     126.018
    ]
   ],
   "text": "Let's build what's next."
  }
 }
};
