// Generated by audio/build_timeline.py — do not edit by hand.
export default {
 "fps": 30,
 "bpm": 100.0,
 "beat": 0.6,
 "duration": 142.8,
 "scenes": [
  {
   "id": "hook",
   "start": 0.0,
   "end": 19.2,
   "lines": [
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6"
   ]
  },
  {
   "id": "intro",
   "start": 19.2,
   "end": 33.6,
   "lines": [
    "i1",
    "i2",
    "i3"
   ]
  },
  {
   "id": "search",
   "start": 33.6,
   "end": 54.0,
   "lines": [
    "s1",
    "s2",
    "s3"
   ]
  },
  {
   "id": "story",
   "start": 54.0,
   "end": 73.2,
   "lines": [
    "t1",
    "t2",
    "t3",
    "t4"
   ]
  },
  {
   "id": "vision",
   "start": 73.2,
   "end": 92.4,
   "lines": [
    "v1",
    "v2",
    "v3"
   ]
  },
  {
   "id": "agri",
   "start": 92.4,
   "end": 111.6,
   "lines": [
    "a1",
    "a2",
    "a3"
   ]
  },
  {
   "id": "docs",
   "start": 111.6,
   "end": 127.2,
   "lines": [
    "d1",
    "d2"
   ]
  },
  {
   "id": "finale",
   "start": 127.2,
   "end": 142.8,
   "lines": [
    "f1",
    "f2",
    "f3",
    "f4"
   ]
  }
 ],
 "lines": {
  "h1": {
   "id": "h1",
   "scene": "hook",
   "start": 1.3,
   "end": 2.455,
   "segs": [
    [
     1.33,
     2.35
    ]
   ],
   "text": "A creative brief."
  },
  "h2": {
   "id": "h2",
   "scene": "hook",
   "start": 2.905,
   "end": 3.965,
   "segs": [
    [
     2.935,
     3.845
    ]
   ],
   "text": "A child's toy."
  },
  "h3": {
   "id": "h3",
   "scene": "hook",
   "start": 4.415,
   "end": 5.415,
   "segs": [
    [
     4.445,
     5.295
    ]
   ],
   "text": "A camera feed."
  },
  "h4": {
   "id": "h4",
   "scene": "hook",
   "start": 5.865,
   "end": 7.075,
   "segs": [
    [
     5.895,
     6.955
    ]
   ],
   "text": "A stack of evidence."
  },
  "h5": {
   "id": "h5",
   "scene": "hook",
   "start": 8.075,
   "end": 11.17,
   "segs": [
    [
     8.105,
     9.455
    ],
    [
     9.805,
     11.085
    ]
   ],
   "text": "Not AI as a feature. AI as the product."
  },
  "h6": {
   "id": "h6",
   "scene": "hook",
   "start": 12.17,
   "end": 18.923,
   "segs": [
    [
     12.2,
     16.33
    ],
    [
     16.73,
     17.43
    ],
    [
     17.61,
     18.86
    ]
   ],
   "text": "Eagerworks AI Studio turns AI capabilities into real products, workflows and measurable outcomes."
  },
  "i1": {
   "id": "i1",
   "scene": "intro",
   "start": 19.7,
   "end": 25.076,
   "segs": [
    [
     19.73,
     21.7
    ],
    [
     21.85,
     23.12
    ],
    [
     23.48,
     25.02
    ]
   ],
   "text": "We're a team of designers and engineers who build digital products, from the first idea to launch."
  },
  "i2": {
   "id": "i2",
   "scene": "intro",
   "start": 25.676,
   "end": 28.449,
   "segs": [
    [
     25.706,
     26.106
    ],
    [
     26.316,
     28.366
    ]
   ],
   "text": "Today, more and more of what we ship runs on AI."
  },
  "i3": {
   "id": "i3",
   "scene": "intro",
   "start": 29.149,
   "end": 32.019,
   "segs": [
    [
     29.179,
     31.949
    ]
   ],
   "text": "Here are a few of the projects we've built for our clients."
  },
  "s1": {
   "id": "s1",
   "scene": "search",
   "start": 34.3,
   "end": 38.13,
   "segs": [
    [
     34.33,
     36.88
    ],
    [
     37.19,
     38.06
    ]
   ],
   "text": "A production team describes the location they need, in their own words."
  },
  "s2": {
   "id": "s2",
   "scene": "search",
   "start": 38.73,
   "end": 47.221,
   "segs": [
    [
     38.76,
     40.55
    ],
    [
     40.95,
     42.06
    ],
    [
     42.41,
     44.76
    ],
    [
     45.05,
     47.15
    ]
   ],
   "text": "AI parses every requirement, searches the catalog, evaluates each location against the brief, and returns a personalized shortlist."
  },
  "s3": {
   "id": "s3",
   "scene": "search",
   "start": 48.521,
   "end": 52.83,
   "segs": [
    [
     48.551,
     50.211
    ],
    [
     50.541,
     52.751
    ]
   ],
   "text": "Then the conversation keeps going, and every reply makes the results sharper."
  },
  "t1": {
   "id": "t1",
   "scene": "story",
   "start": 54.5,
   "end": 58.363,
   "segs": [
    [
     54.53,
     55.39
    ],
    [
     55.7,
     58.27
    ]
   ],
   "text": "For another client, AI turns something physical into something personal."
  },
  "t2": {
   "id": "t2",
   "scene": "story",
   "start": 58.863,
   "end": 61.146,
   "segs": [
    [
     58.893,
     61.053
    ]
   ],
   "text": "A child places a few pieces on a board."
  },
  "t3": {
   "id": "t3",
   "scene": "story",
   "start": 61.746,
   "end": 67.911,
   "segs": [
    [
     61.766,
     63.436
    ],
    [
     63.786,
     65.386
    ],
    [
     65.696,
     67.846
    ]
   ],
   "text": "The system recognizes each one, reasons about how they connect, and writes a story that's entirely theirs."
  },
  "t4": {
   "id": "t4",
   "scene": "story",
   "start": 69.011,
   "end": 71.976,
   "segs": [
    [
     69.041,
     70.131
    ],
    [
     70.401,
     71.891
    ]
   ],
   "text": "We build it end to end, from the app to the story engine."
  },
  "v1": {
   "id": "v1",
   "scene": "vision",
   "start": 73.6,
   "end": 76.245,
   "segs": [
    [
     73.63,
     74.69
    ],
    [
     74.87,
     76.16
    ]
   ],
   "text": "Some problems need more than an API call."
  },
  "v2": {
   "id": "v2",
   "scene": "vision",
   "start": 76.745,
   "end": 83.914,
   "segs": [
    [
     76.775,
     79.145
    ],
    [
     79.625,
     80.965
    ],
    [
     81.175,
     82.465
    ],
    [
     82.655,
     83.855
    ]
   ],
   "text": "For robotics, we build the vision stack itself: hand and face detection, camera and wrist tracking, and custom datasets."
  },
  "v3": {
   "id": "v3",
   "scene": "vision",
   "start": 84.614,
   "end": 89.115,
   "segs": [
    [
     84.644,
     86.694
    ],
    [
     87.044,
     89.034
    ]
   ],
   "text": "Then we train and benchmark every model, until the data is ready to teach a robot."
  },
  "a1": {
   "id": "a1",
   "scene": "agri",
   "start": 92.9,
   "end": 97.114,
   "segs": [
    [
     92.93,
     93.79
    ],
    [
     94.0,
     94.75
    ],
    [
     94.95,
     97.04
    ]
   ],
   "text": "Computer vision turns a camera into a live source of operational data."
  },
  "a2": {
   "id": "a2",
   "scene": "agri",
   "start": 97.664,
   "end": 103.009,
   "segs": [
    [
     97.694,
     99.124
    ],
    [
     99.414,
     100.894
    ],
    [
     101.114,
     102.944
    ]
   ],
   "text": "On a tractor, it detects, counts and measures every plant, and maps exactly where each one is."
  },
  "a3": {
   "id": "a3",
   "scene": "agri",
   "start": 104.509,
   "end": 110.418,
   "segs": [
    [
     104.539,
     105.469
    ],
    [
     105.769,
     108.539
    ],
    [
     108.909,
     110.329
    ]
   ],
   "text": "On the packing line, every pumpkin gets its own ID the moment it appears, and keeps it until it's counted."
  },
  "d1": {
   "id": "d1",
   "scene": "docs",
   "start": 112.1,
   "end": 122.799,
   "segs": [
    [
     112.13,
     113.71
    ],
    [
     114.1,
     115.55
    ],
    [
     115.88,
     119.98
    ],
    [
     120.3,
     121.27
    ],
    [
     121.46,
     122.74
    ]
   ],
   "text": "And when the work lives in documents, AI reads the evidence, maps it to frameworks like SOC 2 and ISO 27001, flags the gaps, and recommends what to fix."
  },
  "d2": {
   "id": "d2",
   "scene": "docs",
   "start": 123.399,
   "end": 126.322,
   "segs": [
    [
     123.429,
     124.959
    ],
    [
     125.219,
     126.259
    ]
   ],
   "text": "So teams know where they stand, before the auditor does."
  },
  "f1": {
   "id": "f1",
   "scene": "finale",
   "start": 127.8,
   "end": 132.099,
   "segs": [
    [
     127.83,
     128.71
    ],
    [
     129.09,
     130.32
    ],
    [
     130.49,
     132.02
    ]
   ],
   "text": "Different problems. One team that designs, builds and ships the whole system."
  },
  "f2": {
   "id": "f2",
   "scene": "finale",
   "start": 133.399,
   "end": 135.019,
   "segs": [
    [
     133.429,
     134.899
    ]
   ],
   "text": "Eagerworks AI Studio."
  },
  "f3": {
   "id": "f3",
   "scene": "finale",
   "start": 135.619,
   "end": 138.148,
   "segs": [
    [
     135.649,
     138.079
    ]
   ],
   "text": "From AI ideas to real-world products."
  },
  "f4": {
   "id": "f4",
   "scene": "finale",
   "start": 139.148,
   "end": 140.516,
   "segs": [
    [
     139.178,
     140.418
    ]
   ],
   "text": "Let's build what's next."
  }
 }
};
