// Generated by audio/build_timeline.py — do not edit by hand.
export default {
 "fps": 30,
 "bpm": 100.0,
 "beat": 0.6,
 "duration": 166.8,
 "scenes": [
  {
   "id": "hook",
   "start": 0.0,
   "end": 19.2,
   "lines": [
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6"
   ]
  },
  {
   "id": "intro",
   "start": 19.2,
   "end": 33.6,
   "lines": [
    "i1",
    "i2",
    "i3"
   ]
  },
  {
   "id": "vision",
   "start": 33.6,
   "end": 52.8,
   "lines": [
    "v1",
    "v2",
    "v3"
   ]
  },
  {
   "id": "agri",
   "start": 52.8,
   "end": 72.0,
   "lines": [
    "a1",
    "a2",
    "a3"
   ]
  },
  {
   "id": "search",
   "start": 72.0,
   "end": 92.4,
   "lines": [
    "s1",
    "s2",
    "s3"
   ]
  },
  {
   "id": "story",
   "start": 92.4,
   "end": 111.6,
   "lines": [
    "t1",
    "t2",
    "t3",
    "t4"
   ]
  },
  {
   "id": "docs",
   "start": 111.6,
   "end": 127.2,
   "lines": [
    "d1",
    "d2"
   ]
  },
  {
   "id": "inhouse",
   "start": 127.2,
   "end": 151.2,
   "lines": [
    "o1",
    "o2",
    "o3",
    "o4"
   ]
  },
  {
   "id": "finale",
   "start": 151.2,
   "end": 166.8,
   "lines": [
    "f1",
    "f2",
    "f3",
    "f4"
   ]
  }
 ],
 "lines": {
  "h1": {
   "id": "h1",
   "scene": "hook",
   "start": 1.3,
   "end": 2.455,
   "segs": [
    [
     1.33,
     2.35
    ]
   ],
   "text": "A creative brief."
  },
  "h2": {
   "id": "h2",
   "scene": "hook",
   "start": 2.905,
   "end": 3.965,
   "segs": [
    [
     2.935,
     3.845
    ]
   ],
   "text": "A child's toy."
  },
  "h3": {
   "id": "h3",
   "scene": "hook",
   "start": 4.415,
   "end": 5.415,
   "segs": [
    [
     4.445,
     5.295
    ]
   ],
   "text": "A camera feed."
  },
  "h4": {
   "id": "h4",
   "scene": "hook",
   "start": 5.865,
   "end": 7.075,
   "segs": [
    [
     5.895,
     6.955
    ]
   ],
   "text": "A stack of evidence."
  },
  "h5": {
   "id": "h5",
   "scene": "hook",
   "start": 8.075,
   "end": 11.17,
   "segs": [
    [
     8.105,
     9.455
    ],
    [
     9.805,
     11.085
    ]
   ],
   "text": "Not AI as a feature. AI as the product."
  },
  "h6": {
   "id": "h6",
   "scene": "hook",
   "start": 12.17,
   "end": 18.923,
   "segs": [
    [
     12.2,
     16.33
    ],
    [
     16.73,
     17.43
    ],
    [
     17.61,
     18.86
    ]
   ],
   "text": "Eagerworks AI Studio turns AI capabilities into real products, workflows and measurable outcomes."
  },
  "i1": {
   "id": "i1",
   "scene": "intro",
   "start": 19.7,
   "end": 25.076,
   "segs": [
    [
     19.73,
     21.7
    ],
    [
     21.85,
     23.12
    ],
    [
     23.48,
     25.02
    ]
   ],
   "text": "We're a team of designers and engineers who build digital products, from the first idea to launch."
  },
  "i2": {
   "id": "i2",
   "scene": "intro",
   "start": 25.676,
   "end": 28.449,
   "segs": [
    [
     25.706,
     26.106
    ],
    [
     26.316,
     28.366
    ]
   ],
   "text": "Today, more and more of what we ship runs on AI."
  },
  "i3": {
   "id": "i3",
   "scene": "intro",
   "start": 29.149,
   "end": 32.019,
   "segs": [
    [
     29.179,
     31.949
    ]
   ],
   "text": "Here are a few of the projects we've built for our clients."
  },
  "v1": {
   "id": "v1",
   "scene": "vision",
   "start": 34.0,
   "end": 36.645,
   "segs": [
    [
     34.03,
     35.09
    ],
    [
     35.27,
     36.56
    ]
   ],
   "text": "Some problems need more than an API call."
  },
  "v2": {
   "id": "v2",
   "scene": "vision",
   "start": 37.145,
   "end": 44.314,
   "segs": [
    [
     37.175,
     39.545
    ],
    [
     40.025,
     41.365
    ],
    [
     41.575,
     42.865
    ],
    [
     43.055,
     44.255
    ]
   ],
   "text": "For robotics, we build the vision stack itself: hand and face detection, camera and wrist tracking, and custom datasets."
  },
  "v3": {
   "id": "v3",
   "scene": "vision",
   "start": 45.014,
   "end": 49.515,
   "segs": [
    [
     45.044,
     47.094
    ],
    [
     47.444,
     49.434
    ]
   ],
   "text": "Then we train and benchmark every model, until the data is ready to teach a robot."
  },
  "a1": {
   "id": "a1",
   "scene": "agri",
   "start": 53.3,
   "end": 57.514,
   "segs": [
    [
     53.33,
     54.19
    ],
    [
     54.4,
     55.15
    ],
    [
     55.35,
     57.44
    ]
   ],
   "text": "Computer vision turns a camera into a live source of operational data."
  },
  "a2": {
   "id": "a2",
   "scene": "agri",
   "start": 58.064,
   "end": 63.409,
   "segs": [
    [
     58.094,
     59.524
    ],
    [
     59.814,
     61.294
    ],
    [
     61.514,
     63.344
    ]
   ],
   "text": "On a tractor, it detects, counts and measures every plant, and maps exactly where each one is."
  },
  "a3": {
   "id": "a3",
   "scene": "agri",
   "start": 64.909,
   "end": 70.818,
   "segs": [
    [
     64.939,
     65.869
    ],
    [
     66.169,
     68.939
    ],
    [
     69.309,
     70.729
    ]
   ],
   "text": "On the packing line, every pumpkin gets its own ID the moment it appears, and keeps it until it's counted."
  },
  "s1": {
   "id": "s1",
   "scene": "search",
   "start": 72.7,
   "end": 76.53,
   "segs": [
    [
     72.73,
     75.28
    ],
    [
     75.59,
     76.46
    ]
   ],
   "text": "A production team describes the location they need, in their own words."
  },
  "s2": {
   "id": "s2",
   "scene": "search",
   "start": 77.13,
   "end": 85.621,
   "segs": [
    [
     77.16,
     78.95
    ],
    [
     79.35,
     80.46
    ],
    [
     80.81,
     83.16
    ],
    [
     83.45,
     85.55
    ]
   ],
   "text": "AI parses every requirement, searches the catalog, evaluates each location against the brief, and returns a personalized shortlist."
  },
  "s3": {
   "id": "s3",
   "scene": "search",
   "start": 86.921,
   "end": 91.23,
   "segs": [
    [
     86.951,
     88.611
    ],
    [
     88.941,
     91.151
    ]
   ],
   "text": "Then the conversation keeps going, and every reply makes the results sharper."
  },
  "t1": {
   "id": "t1",
   "scene": "story",
   "start": 92.9,
   "end": 96.763,
   "segs": [
    [
     92.93,
     93.79
    ],
    [
     94.1,
     96.67
    ]
   ],
   "text": "For another client, AI turns something physical into something personal."
  },
  "t2": {
   "id": "t2",
   "scene": "story",
   "start": 97.263,
   "end": 99.546,
   "segs": [
    [
     97.293,
     99.453
    ]
   ],
   "text": "A child places a few pieces on a board."
  },
  "t3": {
   "id": "t3",
   "scene": "story",
   "start": 100.146,
   "end": 106.311,
   "segs": [
    [
     100.166,
     101.836
    ],
    [
     102.186,
     103.786
    ],
    [
     104.096,
     106.246
    ]
   ],
   "text": "The system recognizes each one, reasons about how they connect, and writes a story that's entirely theirs."
  },
  "t4": {
   "id": "t4",
   "scene": "story",
   "start": 107.411,
   "end": 110.376,
   "segs": [
    [
     107.441,
     108.531
    ],
    [
     108.801,
     110.291
    ]
   ],
   "text": "We build it end to end, from the app to the story engine."
  },
  "d1": {
   "id": "d1",
   "scene": "docs",
   "start": 112.1,
   "end": 122.799,
   "segs": [
    [
     112.13,
     113.71
    ],
    [
     114.1,
     115.55
    ],
    [
     115.88,
     119.98
    ],
    [
     120.3,
     121.27
    ],
    [
     121.46,
     122.74
    ]
   ],
   "text": "And when the work lives in documents, AI reads the evidence, maps it to frameworks like SOC 2 and ISO 27001, flags the gaps, and recommends what to fix."
  },
  "d2": {
   "id": "d2",
   "scene": "docs",
   "start": 123.399,
   "end": 126.322,
   "segs": [
    [
     123.429,
     124.959
    ],
    [
     125.219,
     126.259
    ]
   ],
   "text": "So teams know where they stand, before the auditor does."
  },
  "o1": {
   "id": "o1",
   "scene": "inhouse",
   "start": 127.8,
   "end": 130.957,
   "segs": [
    [
     127.83,
     129.16
    ],
    [
     129.44,
     130.88
    ]
   ],
   "text": "Alongside our client work, we're building products of our own."
  },
  "o2": {
   "id": "o2",
   "scene": "inhouse",
   "start": 131.857,
   "end": 136.294,
   "segs": [
    [
     131.887,
     133.877
    ],
    [
     134.227,
     136.217
    ]
   ],
   "text": "Like a vision system for packing lines that runs on a single overhead camera."
  },
  "o3": {
   "id": "o3",
   "scene": "inhouse",
   "start": 136.794,
   "end": 142.117,
   "segs": [
    [
     136.824,
     138.774
    ],
    [
     139.144,
     140.644
    ],
    [
     140.904,
     142.054
    ]
   ],
   "text": "It detects every apple in every crate, gives each one its own ID, and keeps a running count."
  },
  "o4": {
   "id": "o4",
   "scene": "inhouse",
   "start": 143.017,
   "end": 149.428,
   "segs": [
    [
     143.047,
     145.987
    ],
    [
     146.357,
     148.237
    ],
    [
     148.547,
     149.357
    ]
   ],
   "text": "It can also count fruit as it crosses a line on the conveyor, so the team can follow throughput live, crate by crate."
  },
  "f1": {
   "id": "f1",
   "scene": "finale",
   "start": 151.8,
   "end": 156.099,
   "segs": [
    [
     151.83,
     152.71
    ],
    [
     153.09,
     154.32
    ],
    [
     154.49,
     156.02
    ]
   ],
   "text": "Different problems. One team that designs, builds and ships the whole system."
  },
  "f2": {
   "id": "f2",
   "scene": "finale",
   "start": 157.399,
   "end": 159.019,
   "segs": [
    [
     157.429,
     158.899
    ]
   ],
   "text": "Eagerworks AI Studio."
  },
  "f3": {
   "id": "f3",
   "scene": "finale",
   "start": 159.619,
   "end": 162.148,
   "segs": [
    [
     159.649,
     162.079
    ]
   ],
   "text": "From AI ideas to real-world products."
  },
  "f4": {
   "id": "f4",
   "scene": "finale",
   "start": 163.148,
   "end": 164.516,
   "segs": [
    [
     163.178,
     164.418
    ]
   ],
   "text": "Let's build what's next."
  }
 }
};
